### ISSUE TITLE
是否有相关的文章支持

### ISSUE THREAD

**Issue by Annmixiu** [THUMIG/torch-model-compression#14]
前辈您好，我是模型压缩相关工作的初学者，您的工作十分有创造性，请问本代码是否有相关的paper？

**Comment by gdh1995** [comment]
> 1)  ACNet、CnC、ACBCorner等一系列重参数化方法
> 2）ResRep模型剪枝方法
> 3）CSGD模型剪枝方法

这几个都有论文，比如 2019-ACNet-Strengthening the Kernel Skeletons for Powerful CNN via Asymmetric 。
你可以在学术网站上搜搜“丁霄汉”、`ACNet`

**Comment by Annmixiu** [comment]
好的，谢谢前辈
