### ISSUE TITLE
About how to import self-built models for compression

### ISSUE THREAD

**Issue by Annmixiu** [THUMIG/torch-model-compression#16]
前辈您好，我是模型压缩的初学者，您的方法相当有创造性，目前我在尝试用您的算法剪枝量化自己构建的模型，但与直接调用torchvision.models.resnet50()不同是，报错显示无法找到对应的层，具体报错如下:AttributeError: type object 'Net' has no attribute 'enc_conv1' ；RuntimeError: Can not find the enc_conv1 in model
我目前的具体操作是:
（1）from model.sesnet import Net来调用自建模型中的类（其中sesnet是构建模型的py文件,Net是模型的类）
（2）直接用model=Net来构建模型
（3）根据名称获取nn.Module对象：conv1 = tools.get_object(model, "self.enc_conv1")
debug中显示model={type}<class 'model.sesnet.Net'>，而不是像例子中获得构建好的resnet，关于这个问题可以向您请教下吗

**Comment by gdh1995** [comment]
model 应该是一个 torch.nn.Module 的实例，你这个 `model=Net` 看起来需要改成 `model = Net()`
